### ISSUE TITLE
关于预训练optimization.py 和　google bert 是不是一样的问题

### ISSUE THREAD

**Issue by 652994331** [brightmart/albert_zh#101]
想问问　预训练部分　run_pretraining.py 和　google bert的不同是不是只是模型配置文件不同，结构是一样的呀, 可以直接用google bert 的 optimizaton 吗请问(modeling.py 我理解用albert就好)

**Comment by brightmart** [comment]
不是的哦。albert除了模型有一些变化，预训练任务的构造也有一些差异（主要体现在next sentence prediction这部分，改成了一些）

**Comment by 652994331** [comment]
明白 我看到SOP的部分了 就是想问问 optimization.py 是不是一样



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: brightmart <notifications@github.com&gt;
发送时间: 2020年2月4日 18:12
收件人: brightmart/albert_zh <albert_zh@noreply.github.com&gt;
抄送: 652994331 <652994331@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[brightmart/albert_zh] 关于预训练optimization.py 和　google bert 是不是一样的问题 (#101)




不是的哦。albert除了模型有一些变化，预训练任务的构造也有一些差异（主要体现在next sentence prediction这部分，改成了一些）

**Comment by brightmart** [comment]
optimization.py都是支持大的batch size的通用的优化器，但是代码不是一模一样的

________________________________
发件人: 652994331 <notifications@github.com>
发送时间: 2020年2月5日 10:13
收件人: brightmart/albert_zh <albert_zh@noreply.github.com>
抄送: brightmart <brightmart@hotmail.com>; Comment <comment@noreply.github.com>
主题: Re: [brightmart/albert_zh] 关于预训练optimization.py 和　google bert 是不是一样的问题 (#101)

明白 我看到SOP的部分了 就是想问问 optimization.py 是不是一样



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: brightmart <notifications@github.com&gt;
发送时间: 2020年2月4日 18:12
收件人: brightmart/albert_zh <albert_zh@noreply.github.com&gt;
抄送: 652994331 <652994331@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[brightmart/albert_zh] 关于预训练optimization.py 和　google bert 是不是一样的问题 (#101)




不是的哦。albert除了模型有一些变化，预训练任务的构造也有一些差异（主要体现在next sentence prediction这部分，改成了一些）

―
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

―

**Comment by 652994331** [comment]
好的 感谢
