### ISSUE TITLE
How to create vocab for other language?

### ISSUE THREAD

**Issue by 008karan** [brightmart/albert_zh#13]
Thanks for the implementation! 
I would like to know how you have created vocab for training ALBERT.
I am using Sentencepiece for this but which `model_type` to choose from `bpe,word or char`

**Comment by brightmart** [comment]
hi, we used vocabulary from bert, it is a single word for Chinese. 

you can check bert or xlnet for reference.

**Comment by brightmart** [comment]
in xlnet, it is using sentence piece. you can easily generate vocabulary based on your corpus. check here: <a href="https://github.com/zihangdai/xlnet">xlnet</a>, and then you will have to take a look of tokenizer

you can also check non-english support from bert: https://github.com/google-research/bert/blob/master/multilingual.md

**Comment by lonePatient** [comment]
@008karan  SentencePiece does quite the opposite to WordPiece. From the [documentation](https://github.com/google/sentencepiece/blob/master/README.md). SentencePiece first escapes the whitespace with a meta-symbol "▁" (U+2581) as follows:

`Hello▁World`.

Then, this text is segmented into small pieces, for example:

`[Hello] [▁Wor] [ld] [.]`

Subwords which occur after whitespace (which are also those that most words begin with) are prepended with '▁', while others are unchanged. This excludes subwords which only occur at the beginning of sentences and nowhere else. These cases should be quite rare, however. 

So, in order to obtain a vocabulary analogous to WordPiece, we need to perform a simple conversion, removing "▁" from the tokens that contain it and adding "##"  to the ones that don't.

```python
def parse_sentencepiece_token(token):
    if token.startswith("▁"):
        return token[1:]
    else:
        return "##" + token
```

**Comment by brightmart** [comment]
good job
