### ISSUE TITLE
How to measure the embedding/representation difference between layers?

### ISSUE THREAD

**Issue by LifangD** [brightmart/albert_zh#16]
Can anyone explain how to draw such figure since the L2 distance or cosine similarity is often conducted on the vector rather than the embedding matrix. Besides, how to  measure it on the whole dataset?
Thanks for any suggestions or references~

![image](https://user-images.githubusercontent.com/33337947/66449151-9d794b00-ea86-11e9-930f-95898fa4e219.png)

**Comment by brightmart** [comment]
may be you can take the first position, which is [CLS] token, it represent the sequence of that layer. so that you can have a hidden states as vector to represent that specific layer. 
after you trained the model, or you get a checkpoint from pre-trained model, i think you can measure it, as all the parameters are fixed. it may not relate to a downstream dataset.
